### ISSUE TITLE
[RT-3087] Allow me to specify custom names for link references

### ISSUE THREAD

**Issue by blu3r4y** [dynatrace-oss/invadium#13]
**Acceptance Criteria:**

The recon container has 5 links to kali.org and this is shown like in the attached screenshot.

![image](https://user-images.githubusercontent.com/10400532/187620317-190a5521-bd44-4b97-913a-8f674eee92c3.png)

**Idea:**

How about allowing two variants for specifingy links, as of now, this one:

```yaml
links:
  - https://www.kali.org/tools/nmap/
  - https://www.kali.org/tools/nikto/
  - https://www.kali.org/tools/dirb/
  - https://www.kali.org/tools/sqlmap/
  - https://www.kali.org/tools/commix
```

But, as an alternative, also this one:
```yaml
links:
  - https://www.kali.org/tools/nmap/
  - url: https://www.kali.org/tools/nikto/
    name: nikto
  - url: https://www.kali.org/tools/dirb/
    name: dirb
```

The frontend or backend would need to differentiate if a atomic value is supplied or a url-name object is supplied. If an url-name object is supplied, the custom name is used instead of the hostname.
