### ISSUE TITLE
Invadium UI is blank

### ISSUE THREAD

**Issue by agardnerIT** [dynatrace-oss/invadium#25]
![image](https://user-images.githubusercontent.com/26523841/195797170-7de1de1d-343e-47b7-a9c2-008e36d8be51.png)

**To Reproduce**
```
# Ubuntu box
# update docker compose otherwise it moans about version
sudo apt update  < "/dev/null"
sudo apt install -y ca-certificates curl gnupg lsb-release  < "/dev/null"
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt update  < "/dev/null"
sudo apt install -y docker-compose-plugin  < "/dev/null"

# Clone Repo
git clone https://github.com/dynatrace-oss/invadium

# Start
cd invadium
docker compose up --no-build -d
```

# Env details
```
$ whoami
root
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

**Comment by blu3r4y** [comment]
Hi Adam, thanks for reporting this! :)

Since I am travelling right now, it might take a few more days until I will have time to take a look at this one.

**Comment by blu3r4y** [comment]
Deploying with the default `docker-compose.yaml` currently only supports a local deployment, meaning, it assumes that you host Invadium on `127.0.0.1` and not some other hostname.

I suppose you are exposing Invadium on a different hostname and trying to access it there?

Here is a `docker-compose.yaml` that works in this scenario, however, you need to know your hostname in advance.
Replace `your-invadium-hostname` with the hostname where you are running Invadium. 
We add the following two environment variables:
1. `INVADIUM_CORS_ORIGINS` in the backend to allow the frontend to access it
2. `NEXT_BACKEND_API_URL` to tell the frontend where it can reach the backend

```yaml
version: '3.8'

services:
  invadium-backend:
    container_name: invadium-backend
    image: ghcr.io/dynatrace-oss/invadium-backend:latest
    build: backend
    env_file: ./backend/.env
    environment:
      - INVADIUM_CONFIG_PATH=/config
      - INVADIUM_DOCKER_NETWORK=host
      - INVADIUM_CORS_ORIGINS=["http://your-invadium-hostname:3000"]
    ports:
      - 3001:3001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./exploits/config:/config
  invadium-frontend:
    container_name: invadium-frontend
    image: ghcr.io/dynatrace-oss/invadium-frontend:latest
    build: frontend
    environment:
      - NEXT_BACKEND_API_URL=http://your-invadium-hostname:3001
    ports:
      - 3000:3000
```

I understand that this isn't the most user-friendly way to deploy Invadium, partly because Invadium is best used within a Kubernetes cluster. I will look at possible ways to fix this or at least improve the docs.
